{
 "title": "Event_Instance",
 "description": "shiptrack",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "event_type",
    "query": "select event_type from event_instance_reporting"
   },
   {
    "name": "courierCode",
    "query": " select courierCode from event_instance_reporting"
   },
   {
    "name": "event",
    "query": "select event from event_instance_reporting"
   },
   {
    "name": "executed",
    "query": "select executed from event_instance_reporting"
   },
   {
    "name": "enabled",
    "query": "select enabled from event_instance_reporting"
   }
  ]
 },
 "panels": [
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "tracking_number",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time_start,$__interval,0),\n  sum(total_tracking_number) AS \"total_tracking_number\"\nFROM event_instance_reporting \nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\n  and event in  (${event})\n  and courierCode in  (${courierCode})\n  and executed in  (${executed})\n  and enabled in  (${enabled})\n   \nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "all_retry_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time_start,$__interval,0),\n  sum(retry_count_0) AS \"retry_count_0\",\n  sum(retry_count_1) AS \"retry_count_1\",\n  sum(retry_count_2) AS \"retry_count_2\",\n  sum(retry_count_3) AS \"retry_count_3\",\n  sum(retry_count_4) AS \"retry_count_4\",\n  sum(retry_count_5) AS \"retry_count_5\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\n  and event in  (${event})\n  and courierCode in  (${courierCode})\n  and executed in  (${executed})\n  and enabled in  (${enabled})\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "executed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time_start,$__interval,0),\n  sum(executed) AS \"executed\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\n  and event in  (${event})\n  and courierCode in  (${courierCode})\nGROUP BY 1\norder by 1"
    }
   ]
  },
  {
   "title": "retry_count_0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time_start,$__interval,0),\n  sum(retry_count_0) AS \"retry_count_0\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\n  and event in  (${event})\n  and courierCode in  (${courierCode})\n  and executed in  (${executed})\n  and enabled in  (${enabled})\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "retry_count_1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time_start,$__interval,0),\n  sum(retry_count_1) AS \"retry_count_1\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\n  and event in  (${event})\n  and courierCode in  (${courierCode})\n  and executed in  (${executed})\n  and enabled in  (${enabled})\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "retry_count_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time_start,$__interval,0),\n  sum(retry_count_2) AS \"retry_count_2\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\n  and event in  (${event})\n  and courierCode in  (${courierCode})\n  and executed in  (${executed})\n  and enabled in  (${enabled})\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "retry_count_3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time_start,$__interval,0),\n  sum(retry_count_3) AS \"retry_count_3\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\n  and event in  (${event})\n  and courierCode in  (${courierCode})\n  and executed in  (${executed})\n  and enabled in  (${enabled})\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "retry_count_4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time_start,$__interval,0),\n  sum(retry_count_4) AS \"retry_count_4\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\n  and event in  (${event})\n  and courierCode in  (${courierCode})\n  and executed in  (${executed})\n  and enabled in  (${enabled})\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "retry_count_5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_time_start,$__interval,0),\n  sum(retry_count_5) AS \"retry_count_5\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\n  and event in  (${event})\n  and courierCode in  (${courierCode})\n  and executed in  (${executed})\n  and enabled in  (${enabled})\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Alert Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "tracking_number alert panel",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(created_time_start,$__interval,0),\n  sum(total_tracking_number) AS \"total_tracking_number\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n\n   \nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "retry_count_0",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 44 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_0) AS \"retry_count_0\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)"
    }
   ]
  },
  {
   "title": "total_retry_count_1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 44 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_1) AS \"retry_count_1\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start);"
    }
   ]
  },
  {
   "title": "total _retry_count_2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 44 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_2) AS \"retry_count_2\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start);"
    }
   ]
  },
  {
   "title": "total_retry_count_3",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 44 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_3) AS \"retry_count_3\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start);"
    }
   ]
  },
  {
   "title": "total_retry_count_4",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 44 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_4) AS \"retry_count_4\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start);"
    }
   ]
  },
  {
   "title": "total_retry_count_5",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 44 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_5) AS \"retry_count_5\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start);"
    }
   ]
  },
  {
   "title": "total tracking number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(total_tracking_number) AS \"total_tracking_number\"\nFROM event_instance_reporting\nwhere\n$__timeFilter(created_time_start)"
    }
   ]
  },
  {
   "title": "total_executed_true",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 47 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(executed) AS \"executed\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)"
    }
   ]
  },
  {
   "title": "total_enabled_true",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 47 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(enabled) AS \"enabled\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n"
    }
   ]
  },
  { "title": "Filtered Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "retry_count_0",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 51 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_0) AS \"retry_count_0\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\nand event in  (${event})\nand courierCode in  (${courierCode})\nand executed in  (${executed})\nand enabled in  (${enabled})"
    }
   ]
  },
  {
   "title": "retry_count_1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 51 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_1) AS \"retry_count_1\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\nand event in  (${event})\nand courierCode in  (${courierCode})\nand executed in  (${executed})\nand enabled in  (${enabled})"
    }
   ]
  },
  {
   "title": "retry_count_2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 51 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_2) AS \"retry_count_2\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\nand event in  (${event})\nand courierCode in  (${courierCode})\nand executed in  (${executed})\nand enabled in  (${enabled})"
    }
   ]
  },
  {
   "title": "retry_count_3",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 51 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_3) AS \"retry_count_3\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\nand event in  (${event})\nand courierCode in  (${courierCode})\nand executed in  (${executed})\nand enabled in  (${enabled})"
    }
   ]
  },
  {
   "title": "retry_count_4",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 51 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_4) AS \"retry_count_4\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\nand event in  (${event})\nand courierCode in  (${courierCode})\nand executed in  (${executed})\nand enabled in  (${enabled})"
    }
   ]
  },
  {
   "title": "retry_count_5",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 51 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(retry_count_5) AS \"retry_count_5\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\nand event in  (${event})\nand courierCode in  (${courierCode})\nand executed in  (${executed})\nand enabled in  (${enabled})"
    }
   ]
  },
  {
   "title": "total_tracking_number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 54 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(total_tracking_number) AS \"total_tracking_number\"\nFROM event_instance_reporting\nwhere\n$__timeFilter(created_time_start)\nand event_type in  (${event_type})\nand event in  (${event})\nand courierCode in  (${courierCode})\nand executed in  (${executed})\nand enabled in  (${enabled})"
    }
   ]
  },
  {
   "title": "total_executed_true",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 54 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(executed) AS \"executed\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\nand event in  (${event})\nand courierCode in  (${courierCode})\nand executed in  (${executed})\nand enabled in  (${enabled})"
    }
   ]
  },
  {
   "title": "total_enabled_true",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 54 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(enabled) AS \"enabled\"\nFROM event_instance_reporting\nWHERE\n  $__timeFilter(created_time_start)\n  and event_type in  (${event_type})\nand event in  (${event})\nand courierCode in  (${courierCode})\nand executed in  (${executed})\nand enabled in  (${enabled})"
    }
   ]
  }
 ]
}